version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openaibot
    restart: always
    environment:
      - MATTERMOST_BASE_URL
      - MATTERMOST_BOT_TOKEN
      - OPENAI_API_KEY
      - OPENAI_BASE_URL
      - OPENAI_ORGANIZATION
      - OPENAI_RETRY_COUNT
      - LOG_LEVEL
      - CHAT_MAX_TOKENS
