openai:
  base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
  api-key: ${OPENAI_API_KEY}
  organization: ${OPENAI_ORGANIZATION:}
  retry-count: ${OPENAI_RETRY_COUNT:3}
chat:
  max-tokens: ${CHAT_MAX_TOKENS:500}
bot:
  mattermost:
    url: ${MATTERMOST_BASE_URL}
    token: ${MATTERMOST_BOT_TOKEN}
    mentions: # bot will react to these mentions
      - "@chatgptbot"
    channels: # allowed channels to answer
      - chatgpt
      - testchatgpt
logging:
  level:
    com.pushkin: ${LOG_LEVEL:info}
spring:
  profiles:
    active: prod
