openai:
  api-key: ${OPENAI_API_KEY}
  organization: ${OPENAI_ORGANIZATION??:}
  retry-count: ${OPENAI_RETRY_COUNT??:3}
bot:
  mattermost:
    url: ${MATTERMOST_BASE_URL}
    token: ${MATTERMOST_BOT_TOKEN}
    mentions: # bot will react to these mentions
      - "@chatgptbot"
    channels: # allowed channels to answer
      - chatgpt
logging:
  level:
    com.pushkin: ${LOG_LEVEL??:info}
spring:
  profiles:
    active: prod
